server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pet
    password: petshelter1234
    url: jdbc:mysql://localhost:3306/pet_shelter
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB

logging:
  level:
    org:
      springframework:
        security: DEBUG

